export const makeError = (details) => () => {
  const error = new Error('NOT_ALLOWED');
  error.details = details;
  return error;
};

export const errors = {
  Diary: {
    RECORD_ALREADY_EXISTS: 'RECORD_ALREADY_EXISTS',
    RECORD_DUPLICATE: 'RECORD_DUPLICATE',
    DIARY_CLOSED: 'DIARY_CLOSED',
    RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
    RECORD_HAS_EQUAL_NEIGHTBORS: 'RECORD_HAS_EQUAL_NEIGHTBORS',
    RECORD_HAS_LIMITED_SCOPE: 'RECORD_HAS_LIMITED_SCOPE',
    NEW_RECORD_ALREADY_EXISTS: 'NEW_RECORD_ALREADY_EXISTS',
    NEW_RECORD_DUPLICATE: 'NEW_RECORD_DUPLICATE',
    DIARY_NOT_STARTED: 'DIARY_NOT_STARTED',
    DIARY_HAS_RECORDS_LATER: 'DIARY_HAS_RECORDS_LATER',
    DIARY_NOT_CLOSED: 'DIARY_NOT_CLOSED',
  },
  Seller: {
    APPOINTMENT_ALREADY_EXISTS: 'APPOINTMENT_ALREADY_EXISTS',
    APPOINTMENT_DUPLICATE: 'APPOINTMENT_DUPLICATE',
    CARRER_CLOSED: 'CARRER_CLOSED',
    APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
    APPOINTMENT_HAS_EQUAL_NEIGHTBORS: 'APPOINTMENT_HAS_EQUAL_NEIGHTBORS',
    APPOINTMENT_HAS_LIMITED_SCOPE: 'APPOINTMENT_HAS_LIMITED_SCOPE',
    NEW_APPOINTMENT_ALREADY_EXISTS: 'NEW_APPOINTMENT_ALREADY_EXISTS',
    NEW_APPOINTMENT_DUPLICATE: 'NEW_APPOINTMENT_DUPLICATE',
    SELLER_NOT_RECRUITED: 'SELLER_NOT_RECRUITED',
    SELLER_HAS_APPOINTMENTS_LATER: 'SELLER_HAS_APPOINTMENTS_LATER',
    SELLER_NOT_DISSMISSED: 'SELLER_NOT_DISSMISSED',
  },
  Post: {
    PIECE_RATE_ALREADY_EXISTS: 'PIECE_RATE_ALREADY_EXISTS',
    PIECE_RATE_DUPLICATE: 'PIECE_RATE_DUPLICATE',
    PIECE_RATE_NOT_FOUND: 'PIECE_RATE_NOT_FOUND',
    PIECE_RATE_HAS_EQUAL_NEIGHTBORS: 'PIECE_RATE_HAS_EQUAL_NEIGHTBORS',
    PIECE_RATE_HAS_LIMITED_SCOPE: 'PIECE_RATE_HAS_LIMITED_SCOPE',
    NEW_PIECE_RATE_ALREADY_EXISTS: 'NEW_PIECE_RATE_ALREADY_EXISTS',
    NEW_PIECE_RATE_DUPLICATE: 'NEW_PIECE_RATE_DUPLICATE',
  },

  // exapmles
  // articleAlreadyBanned: makeError('ARTICLE_BANNED'),
  // articleNotBanned: makeError('ARTICLE_NOT_BANNED'),
  // articleAlreadyApproved: makeError('ARTICLE_ALREADY_APPROVED'),
  // articleNotApproved: makeError('ARTICLE_NOT_APPROVED'),
  // articleAlreadyRated: makeError('ARTICLE_ALREADY_RATED'),
  // articleNotRated: makeError('ARTICLE_NOT_RATED'),
  // reviewProcessAlreadyCompleted: makeError('REVIEW_PROCESS_ALREADY_COMPLETED'),
  // reviewProcessNotCompleted: makeError('REVIEW_PROCESS_NOT_COMPLETED'),
  // reviewAlreadyRated: makeError('REVIEW_ALREADY_RATED'),
  // reviewNotRated: makeError('REVIEW_NOT_RATED'),
  // userAlreadyRated: makeError('USER_ALREADY_RATED'),
  // userNotRated: makeError('USER_NOT_RATED'),
  // userIsNotOwner: makeError('USER_IS_NOT_OWNER'),
  // permisionDenied: makeError('PERMISSION_DENIED'),
  // reviewerAlreadyListed: makeError('REVIEWER_ALREADY_LISTED'),
  // reviewerNotListed: makeError('REVIEWER_NOT_LISTED'),
  // maxArticleReviewersReached: makeError('MAX_ARTICLE_REVIEWERS_REACHED'),
  // editorAlreadyInvited: makeError('EDITOR_ALREADY_INVITED'),
  // editorNotInvited: makeError('EDITOR_NOT_INVITED'),
  // editorAlreadyConfirmed: makeError('EDITOR_ALREADY_CONFIRMED'),
  // editorNotListed: makeError('EDITOR_NOT_LISTED'),
  // stageTooLarge: makeError('STAGE_TOO_LARGE'),
  // stageNotDefined: makeError('STAGE_NOT_DEFINED'),
  // stageNotFinal: makeError('STAGE_NOT_FINAL'),
};
